### PR TITLE
work on protozfitsreader

### PR DESCRIPTION
**Pull request by dneise**
# Work in progress, do not merge

I open this PR so people can have a look already now. Tests most likely do not pass.
I started this as a refactoring, so change style not function, nor interfaces. 
But while reading, I think I spotted a bug, c.f. #44.

Remarks or Questions are very welcome.

### CODE REVIEW

**Comment by dneise** [comment]
I totally agree. Actually I will write the tests first .. so there will be a new PR ... with a couple of tests on the "old" version of this.

**Comment by dneise** [comment]
The we can first look at the tests and see if trust them ... and then we can apply the tests on this new version and *home* the new version still passes them all.

**Comment by dneise** [comment]
Now this branch is passing the same tests, as the current master. 

Of course, since I changed the interface, also the tests needed to be changed: 
A lot of these:
```
zfits = ZFile(example_file_path)
stuff = [zfits.get_stuff() for __ in zfits.move_to_next_event()]
```
were changed into these:
```
stuff = [event.stuff for event in ZFile(example_file_path)]
```

**Comment by dneise** [comment]
BUT: there is one value, which is now -1, and was 0 before:
`num_channels` or `num_gains`. 

I have no idea if zero or minus-one is correct. Strange are both, I would have expected 1.

**Comment by dneise** [comment]
The test for `num_gains` I have marked as "expected to fail" since I have no idea which value should come out of that

**Comment by calispac** [comment]
`num_gains` is the number of amplification channels per pixel. Some cameras have low and high gain. we only have 1. So num_gains should be 1

**Comment by calispac** [comment]
> BUT: there is one value, which is now -1, and was 0 before:
num_channels or num_gains.

I don't know what is the diff. between the two

**Comment by dneise** [comment]
Ha! found it.

So this is how it is in the current master:

    data.inst.num_channels[tel_id] = zfits.event.num_gains

so something called `num_gains` is assigned to something called `num_channels`. **and**  `zfits` has this

    class Zfile:
        def get_num_channels(self):
            return self._get_numpyfield(self.event.head.numGainChannels)

Here when one calls `get_num_channels` one actually gets `numGainChannels`

-----

This confused me and when refactoring the protozfitsreader, i.e. `ZFile` I **wrongly** assumed `get_num_channels` would be used like this:

    data.inst.num_channels[tel_id] = zfits.get_num_channels()

But it is not! It is not used **at all**.

----

Solved this now... The value is still 0 and not 1 .. in master and in this branch

**Comment by calispac** [comment]
@Etienne12345 Do you know why num_channels is 0 not 1 ?

**Comment by dneise** [comment]
I've added a test, that benchmarks `zfits_event_source` on a 100 event file, with and without `expert_mode==True`. 

Both are more or less equally fast.

**Comment by dneise** [comment]
Ah i think this is ready now, sorry

**Comment by calispac** [comment]
Does this look correct now ?

**Pull request merged**
