### PR TITLE
add docopt

### PR DESCRIPTION
**Pull request by calispac**
Adding docopt to environment.yml. Which version is needed?
Reported by @sagreus

### CODE REVIEW

**Comment by dneise** [comment]
I have 0.6.2 ... but 0.6 should be fine.
Any version should be fine, I think

**Comment by dneise** [comment]
@sagreus thanks for reporting! :+1

**Comment by sagreus** [comment]
@dneise 
conda version : 4.3.27

**Comment by dneise** [comment]
Ah I see... 
To my understanding that version already has docopt included: 
https://docs.anaconda.com/anaconda/packages/old-pkg-lists/4.3.1/py35

Hm .. I don't get it .. anyway including it in the env.yml is certainly correct ... somehow.

**Pull request merged**
