### PR TITLE
removed .idea/ folder

### PR DESCRIPTION
**Pull request by calispac**
this just to remove the folder digicampipe/.idea.

### CODE REVIEW

**Comment by calispac** [comment]
ready to merge

**Comment by dneise** [comment]
adding something to the `.gitignore` file does not remove it from the repo.

    git rm path/to/stuff/to/remove*

this removes some stuff.

Adding something to the gitignore should help people to not accidentally add something when doing

    git add some/new/folder

Because, when adding a new folder, everything inside is added. One can avoid that by adding stuff explicitely

    git add some/new/folder/*.py

for example only adds py-files ...

**Comment by dneise** [comment]
Do you still want to keep `digicampipe/.idea/*` in the gitignore?

**Comment by calispac** [comment]
digicampipe/.idea/ is a folder built by PyCharm (my IDE). Is it useful to add it in the .gitignore ?

**Pull request merged**
