### PR TITLE
Lid ccd pep8

### PR DESCRIPTION
**Pull request by dneise**
just pep8

### CODE REVIEW

**Comment by dneise** [comment]
Thanks for approval, but the tests are failing

**Comment by dneise** [comment]
I am currently looking why they fail ...

**Comment by dneise** [comment]
works on my machine, so ... maybe it also works now on travis, dunno

**Comment by dneise** [comment]
@yrenier are you currently working on something in the lid_ccd branch? Otherwise, I would merge this now.

**Comment by yrenier** [comment]
I merged it XD

**Pull request merged**
