### PR TITLE
Install protozfitsreader v0.41.1

### PR DESCRIPTION
**Pull request by dneise**
There was still a problem with the dependencies of "rawzfitsreader.[...].so".
They should now be solved in protozfitsreader v.0.41.1 which is installed after this PR

### CODE REVIEW

**Comment by dneise** [comment]
I think the environment.yml can be reduced in size a bit .. c.f. https://github.com/dneise/protozfitsreader/blob/master/environment.yml

**Comment by dneise** [comment]
I think we should merge this.

The diff is small.

I do two more tests on travis: basically trying to "import protozfitsreader" 

This did not work before...

I had to modify the RPATH inside the rawzfitsreader.[...].so in the protozfitsreader repo ... this was done in v0.41.1

**Comment by dneise** [comment]
This should solve #52

**Comment by calispac** [comment]
Nice that we have releases of protozfitsreader. We can keep track of the new fields added.

**Comment by dneise** [comment]
Well Etienne is already keeping track with his release number.

Actually I destroyed his versioning system, when moving the contents of his tarball into a git repo. and said in our requirements.txt:

    --e git+https://github.com/dneise/protozfitsreader.git#egg=protozfitsreade

Only now I realized that was not very good (actually it was bullshit) ... and I reintroduced what Etienne already had done:

    +https://github.com/dneise/protozfitsreader/archive/v0.41.1.tar.gz

**Pull request merged**
